title: Yihan (Hank) Tang 
logo: /assets/img/personal_photo.png
description: I am an enthusiast in AI for Healthcare and Natural Language Processing (NLP).
show_downloads: true 
theme: jekyll-theme-minimal
